services:
  postgres:
    image: 'cleisonfmelo/postgres-pg-cron:latest' # https://hub.docker.com/r/cleisonfmelo/postgres-pg-cron [upon pg16]
    restart: always
    environment:
      POSTGRES_DB: votacao
      POSTGRES_PASSWORD: passwd123
      POSTGRES_USER: postgres
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: