services:
  postgres:
    image: 'timescale/timescaledb:latest-pg17'
    restart: always
    environment:
      POSTGRES_DB: votacao
      POSTGRES_PASSWORD: passwd123
      POSTGRES_USER: pguser
    volumes:
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'